### PR TITLE
Added dark theme functionality.Seamlessly integrated with the current frontend,without disturbing other features.

### PR DESCRIPTION
**Pull request by pranavraikar01**
### Added Dark Theme Functionality

- Implemented a dark theme toggle button in the `Header` component.
- The dark mode is applied globally, affecting the entire application without disturbing existing features.
- Used `useState` and `useEffect` to manage the theme state, with seamless integration into the current frontend.
- Icons dynamically switch between sun and moon based on the selected theme using `react-icons` library.
- Ensured that all other functionalities, including authentication and navigation, remain unaffected.

**Note:** The dark theme toggle is currently available in the `Header`, which is not present on the login or signup pages. If you would like the same dark theme functionality on those pages, it can be easily implemented as well.

This enhancement improves the user experience by allowing a theme switch, enhancing accessibility and usability.

Please let me know if you'd like to extend this feature to the login and signup pages.

### CODE REVIEW

**Comment by pranavraikar01** [comment]
Hey, please accept my pull request as this enhancement improves the user experience by allowing a theme switch, enhancing accessibility and usability.

**Comment by pranavraikar01** [comment]
image

image

**Comment by AliBigdeli** [comment]
awesome job man thanks!

**Comment by pranavraikar01** [comment]
Thanks, @AliBigdeli Glad I could contribute. Looking forward to collaborating more in the future!

**Pull request merged**
